--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: basic-org1
  labels:
    app: basic-org1
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-basic-org1
