kind: Service
apiVersion: v1
metadata:
    name: orderer5
    labels:
        run: orderer5
spec:
    selector:
        name: orderer5
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 7050
          name: grpc