apiVersion: v1
kind: Service
metadata:
  name: ca-org1
  labels:
    app: ca-org1
spec:
  type: ClusterIP
  selector:
    app: ca-org1
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054