apiVersion: v1
kind: Service
metadata:
  name: ca-orderer
  
  labels:
    app: ca-orderer
spec:
  type: ClusterIP
  selector:
    app: ca-orderer
  ports:
    - protocol: TCP
      targetPort: 10054
      port: 10054