apiVersion: v1
kind: Service
metadata:
  name: ca-org3
  
  labels:
    app: ca-org3
spec:
  type: ClusterIP
  selector:
    app: ca-org3
  ports:
    - protocol: TCP
      targetPort: 9054
      port: 9054